--CRIAR BANCO DE DADOS
CREATE DATABASE MATERIA

--ENTRAR NO BANCO CRIADO
USE MATERIA
GO

--USAR A MASTER PARA CONSEGUIR DROPAR O BANCO DE DADOS
USE MASTER
GO

--DELETAR O BANCO DE DADOS
DROP DATABASE MATERIA

--CRIAR UM NOVO BANCO
CREATE DATABASE ESCOLA

--CRIAR TABELA 
CREATE TABLE MATERIA (ID_MATERIA BIGINT PRIMARY KEY NOT NULL,
					  NOME_MATERIA VARCHAR(50) NOT NULL)

CREATE TABLE PROFESSOR(ID_PROFESSOR BIGINT PRIMARY KEY NOT NULL, 
					  NOME_PROFESSOR VARCHAR(50) NOT NULL,
					  RG_PROFESSOR VARCHAR(10) NOT NULL,
					  ENDERECO_PROFESSOR VARCHAR(100) NOT NULL,
					  ID_MATERIA BIGINT FOREIGN KEY REFERENCES MATERIA(ID_MATERIA))



--ALTERAR TABELA
ALTER TABLE PROFESSOR
DROP COLUMN ENDERECO_PROFESSOR 

----OBSERVAR A TABELA----
--SELECT*FROM PROFESSOR
--SELECT*FROM ALUNO
--SELECT*FROM NOTA
--SELECT*FROM MATERIA 


--EXERCICIO CRIE 2 TABELAS ('ALUNO' E 'NOTA') E FAÇA UM FOREIGN KEY EM NOTA PARA TODAS AS TABELAS!





--RESPOSTA
CREATE TABLE ALUNO (ID_ALUNO BIGINT PRIMARY KEY NOT NULL, 
				    NOME_ALUNO VARCHAR(50) NOT NULL,
					RG_ALUNO VARCHAR(10) NOT NULL)

CREATE TABLE NOTA (ID_NOTA BIGINT PRIMARY KEY NOT NULL, 
				   NOTA DECIMAL(2,1) NOT NULL,
				   ID_MATERIA BIGINT FOREIGN KEY REFERENCES MATERIA(ID_MATERIA),
				   ID_ALUNO BIGINT FOREIGN KEY REFERENCES ALUNO(ID_ALUNO),
				   ID_PROFESSOR BIGINT FOREIGN KEY REFERENCES PROFESSOR(ID_PROFESSOR))




Equipe VERMELHA

Planejamento Luís (teórica)
- O que é SQL?
- O que é Banco de Dados?
- Qual é a diferença do .SQL e outro arquivo?
- O que é o SGBD?
- O que é Sql Server?
- Tabelas Relacionais

- DDL(prática)
-CREATE DATABASE    
-DROP DATABASE 
-CREATE TABLE 
-ALTER TABLE
-BIGINT
-VARCHAR
- NOT NULL
-PRIMARY KEY
-FOREING KEY(REFERENCES)

obs: valores da cognizant
